[[repo]]
path = '~/dotfiles'

[repo.pre]
check = ['pull']
remote = { branch = 'master', name = 'origin' }

[repo.post]
check = ['commit', 'push']
remote = { branch = 'master', name = 'origin' }

[[repo]]
path = '~/shinshu_works'

[repo.pre]
check = ['pull']
remote = { branch = 'master', name = 'origin' }

[repo.post]
check = ['commit', 'push']
remote = { branch = 'master', name = 'origin' }
