[pre]
[[pre.repo]]
path = '~/dotfiles'
[pre.repo.data]
check = ['pull']
local = 'master'
remote = { branch = 'master', name = 'origin' }

[[pre.repo]]
path = '~/workspace/prepost'
[pre.repo.data]
check = ['pull']
local = 'master'
remote = { branch = 'master', name = 'origin' }

[post]
[[post.repo]]
path = '~/dotfiles'
[post.repo.data]
check = ['pull']
local = 'master'
remote = { branch = 'master', name = 'origin' }

[[post.repo]]
path = '~/workspace/prepost'
[post.repo.data]
check = ['pull']
local = 'master'
remote = { branch = 'master', name = 'origin' }
