[pre]
[[pre.repo]]
path = '~/dotfiles'
check = ['pull']
data = { local = 'master', remote = { branch = 'master', name = 'origin' }}

[[pre.repo]]
path = '~/workspace/prepost'
check = ['pull']
data = { local = 'master', remote = { branch = 'master', name = 'origin' }}

[post]
[[post.repo]]
path = '~/dotfiles'
check = ['push']
data = { local = 'master', remote = { branch = 'master', name = 'origin' }}

[[post.repo]]
path = '~/workspace/prepost'
check = ['push']
data = { local = 'master', remote = { branch = 'master', name = 'origin' }}
