[[repo]]
path = '~/dotfiles'

[repo.pre]
branch = 'master'
check = ['pull']

[repo.post]
branch = 'master'
check = ['commit', 'push']

[[repo]]
path = '~/shinshu_works'

[repo.pre]
branch = 'master'
check = ['pull']

[repo.post]
branch = 'master'
check = ['commit', 'push']
